### ISSUE TITLE
xmbc-earthcam streams not working

### ISSUE THREAD

**Issue by sebastianlutter** [idleloop-github/xbmc-earthcam#5]
I use official version 1.0.2 on Kodi 18.4. I run a mediastation build with gentoo x86_64 as OS.

When I try to start any stream I get into kodi.log:
```
2019-11-19 20:14:12.109 T:140024901256960   ERROR: plugin.video.earthcam-1.0.2-openURL Failed! <urlopen error no host given> ,Traceback (most recent call last):
                                              File "/home/lutters/.kodi/addons/plugin.video.earthcam/resources/lib/earthcam.py", line 70, in openURL
                                                response = urllib2.urlopen(request, timeout = TIMEOUT).read()
                                              File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib64/python2.7/urllib2.py", line 427, in open
                                                req = meth(req)
                                              File "/usr/lib64/python2.7/urllib2.py", line 1126, in do_request_
                                                raise URLError('no host given')
                                            URLError: <urlopen error no host given>
2019-11-19 20:14:12.382 T:140026149024128   ERROR: Previous line repeats 4 times.
2019-11-19 20:14:12.382 T:140026149024128  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.earthcam/?url=http%3Ahttps%3A%2F%2Fvideos3.earthcam.com%2Ffecnetwork%2F10811.flv%2Fplaylist.m3u8&mode=9&name=Moshi%2C+Tanzania+-+Mount+Kilimanjaro+Cam%2C+Tanzania+Live+%28HLS%29
2019-11-19 20:14:12.382 T:140025817118464  NOTICE: Creating InputStream
2019-11-19 20:14:12.382 T:140025817118464 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.earthcam/?url=http%3Ahttps%3A%2F%2Fvideos3.earthcam.com%2Ffecnetwork%2F10811.flv%2Fplaylist.m3u8&mode=9&name=Moshi%2C+Tanzania+-+Mount+Kilimanjaro+Cam%2C+Tanzania+Live+%28HLS%29
2019-11-19 20:14:12.382 T:140025817118464   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.earthcam/?url=http%3Ahttps%3A%2F%2Fvideos3.earthcam.com%2Ffecnetwork%2F10811.flv%2Fplaylist.m3u8&mode=9&name=Moshi%2C+Tanzania+-+Mount+Kilimanjaro+Cam%2C+Tanzania+Live+%28HLS%29]
2019-11-19 20:14:12.382 T:140025817118464  NOTICE: CVideoPlayer::OnExit()
2019-11-19 20:14:12.488 T:140026149024128  NOTICE: CVideoPlayer::CloseFile()
2019-11-19 20:14:12.488 T:140026149024128  NOTICE: VideoPlayer: waiting for threads to exit
2019-11-19 20:14:12.488 T:140026149024128  NOTICE: VideoPlayer: finished waiting
```

Since it complains ```unsupported protocol(plugin) in plugin://plugin.video.earthcam/?url=``` I guess it has something to do with HLS. I don't think this is a bug, can you give me a hint what might be wrong on my side?

Thanks

**Comment by idleloop-github** [comment]
> I use official version 1.0.2 on Kodi 18.4.

Well, official version [by Lunatixz is another version](https://github.com/idleloop-github/xbmc-earthcam/issues/2), not this one :-)
You may lack HLS support: install addon "InputStream Adaptative" and/or [take a look at these notes](https://github.com/idleloop-github/xbmc-earthcam#enable-hls-playing) to see if something apply to your case.
If everything fails, you can try [my addon](https://github.com/idleloop-github/xbmc-earthcam#installation), which supports both RTMP and HLS.
